name: Deno CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      WAKATIME_API_KEY: ${{ secrets.PRODUCTION.WAKATIME_API_KEY }}
      PORT: 8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Deno script
        run: deno run --allow-net --allow-env main.ts
